
module.exports = (sequelize, Sequelize) => {
    const Sector = sequelize.define('sector', {
        title: {type: Sequelize.STRING},
        value: {type: Sequelize.STRING},
    });

    Sector.sync();

    Sector.bulkCreate([
        {title: 'Manufacturing', value: '1'},
        {title: 'Construction materials', value: '19'},
        {title: 'Electronics and Optics', value: '18'},
        {title: 'Food and Beverage', value: '6'},
        {title: 'Bakery & confectionery products', value: '342'},
        {title: 'Beverages', value: '43'},
        {title: 'Fish & fish products', value: '42'},
        {title: 'Meat & meat products', value: '40'},
        {title: 'Milk & dairy products', value: '39'},
        {title: 'Otherrr', value: '437'},
        {title: 'Sweets & snack food', value: '378'},
        {title: 'Furniture', value: '13'},
        {title: 'Bathroom/sauna', value: '389'},
        {title: 'Bedroom', value: '385'},
        {title: 'Children room', value: '390'},
        {title: 'Kitchen', value: '98'},
        {title: 'Living room', value: '101'},
        {title: 'Office', value: '392'},
        {title: 'Other (Furniture)', value: '394'},
        {title: 'Outdoor', value: '341'},
        {title: 'Project furniture', value: '99'},
        {title: 'Machinery', value: '12'},
        {title: 'Machinery components', value: '94'},
        {title: 'Machinery equipment/tools', value: '91'},
        {title: 'Manufacture of machinery', value: '224'},
        {title: 'Maritime', value: '97'},
        {title: 'Aluminium and steel workboats', value: '271'},
        {title: 'Boat/Yacht building', value: '269'},
        {title: 'Ship repair and conversion', value: '230'},
        {title: 'Metal structures', value: '93'},
        {title: 'Otherr', value: '508'},
        {title: 'Repair and maintenance service', value: '227'},
        {title: 'Metalworking', value: '11'},
        {title: 'Construction of metal structures', value: '67'},
        {title: 'Houses and buildings', value: '263'},
        {title: 'Metal products', value: '267'},
        {title: 'Metal works', value: '542'},
        {title: 'CNC-machining', value: '75'},
        {title: 'Forgings Fasteners', value: '62'},
        {title: 'Gas Plasma Laser cutting', value: '69'},
        {title: 'MIG TIG Aluminum welding', value: '66'},
        {title: 'Plastic and Rubber', value: '9'},
        {title: 'Packaging', value: '54'},
        {title: 'Plastic goods', value: '556'},
        {title: 'Plastic processing technology', value: '559'},
        {title: 'Blowing', value: '55'},
        {title: 'Moulding', value: '57'},
        {title: 'Plastics welding and processing', value: '53'},
        {title: 'Plastic profiles', value: '560'},
        {title: 'Printing', value: '5'},
        {title: 'Advertising', value: '148'},
        {title: 'Book/Periodicals printing', value: '150'},
        {title: 'Labelling and packaging printing', value: '145'},
        {title: 'Textile and Clothing', value: '7'},
        {title: 'Clothing', value: '44'},
        {title: 'Textile', value: '45'},
        {title: 'Wood', value: '8'},
        {title: 'Other (Wood)', value: '337'},
        {title: 'Wooden building materials', value: '51'},
        {title: 'Wooden houses', value: '47'},
        {title: 'Other', value: '3'},
        {title: 'Creative industries', value: '37'},
        {title: 'Energy technology', value: '29'},
        {title: 'Environment', value: '33'},
        {title: 'Service', value: '2'},
        {title: 'Business services', value: '25'},
        {title: 'Engineering', value: '35'},
        {title: 'Information Technology and Telecommunications', value: '28'},
        {title: 'Data processing Web portals E-marketing', value: '581'},
        {title: 'Programming Consultancy', value: '576'},
        {title: 'Software Hardware', value: '121'},
        {title: 'Telecommunications', value: '122'},
        {title: 'Tourism', value: '22'},
        {title: 'Translation services', value: '141'},
        {title: 'Transport and Logistics', value: '21'},
        {title: 'Air', value: '110'},
        {title: 'Rail', value: '114'},
        {title: 'Road', value: '112'},
        {title: 'Water', value: '113'},
    ]).then(() => {
        console.log("Sector bulkCreate done..");
    });

    return Sector;
};
